### PR TITLE
support of int and long types

### PR DESCRIPTION
**Pull request by AJIXuMuK**
`int` and `long` are also correct types for the log entity.

### CODE REVIEW

**Comment by Zimmergren** [comment]
Hey @AJIXuMuK , I'll take a look and run through some additional integration tests with these changes. 
I have used the official docs and the mentioned data types ( https://docs.microsoft.com/en-us/azure/azure-monitor/platform/data-collector-api#record-type-and-properties ) - do you have other references for additional data types?

**Comment by AJIXuMuK** [comment]
@Zimmergren technically, as this is JSON, we have a `number` type. So, we can covert `int`, `long`, and `double` to it. 
I also looked at export from log tables to PowerBI. And it shows mappings for `Int32`, `Int64`, and `Double`.

**Comment by Zimmergren** [comment]
Thanks for the insights @AJIXuMuK. 
I have ran all integration tests E2E and indeed it works. Merging this now, and then I'll add some additional E2E tests to ensure we can cover these types as well.

Thanks for your contribution! 👍

**Comment by AJIXuMuK** [comment]
Awesome!

Sorry for not adding tests right away to the PR.

**Comment by Zimmergren** [comment]
Don't worry about it - it's straight forward. 
I will make a new release today with these changes 🎉

**Comment by Zimmergren** [comment]
It looks like the long type isn't fully working. 

I am setting up an end-to-end integration test with the following long value: 

```csharp
new DemoEntity
                {
                    Criticality = "e2ecriticality",
                    Message = testIdentifierEntries,
                    SystemSource = "e2etest",
                    Priority = 2,
                    VerificationNumber = long.MaxValue - 1
                }
```

the long.MaxValue is `9223372036854775806`, but the data returned are cut off, so it means we're getting flawed data into the LAW, where I also verified that the long number has been rounded and cut off. The outcome is as below, and hence we cannot use long datatypes safely:

```csharp
Assert.AreEqual failed. Expected:<9223372036854775806>. Actual:<9223372036854780000>. 
```

**Pull request merged**
